### ISSUE TITLE
Script does not update package.json

### ISSUE THREAD

**Issue by gruselhaus** [mikeal/merge-release#12]
Hi Mikeal,

great tool! 

Unfortunately it does not update our package.json file even though the new tag was pushed to the repo.

Here is a link to that run: https://github.com/pegasusspiele/missing-orders/commit/a36efb11d46c0895d09b1cb9fa70ec3c6058e7f1/checks?check_suite_id=380841068

Could you investigate this situation please?

**Comment by mikeal** [comment]
This is intentional. Since every commit is published by default it would create a tremendous amount of noise to add a commit to master for every release since it would effectively double the commit logs. Instead, the package.json change is committed and pushed as a tag and then reverted in master. In most projects, you simple set the master package.json version to `0.0.0-dev` in order to avoid any confusion.

**Comment by gruselhaus** [comment]
Ok, thank you for the explanation!
