### ISSUE TITLE
Update the package.json file and PR?

### ISSUE THREAD

**Issue by MrCoder** [mikeal/merge-release#28]
Is it possible for this action to update the package.json and create a pull request? Otherwise, the published version and the version in the package.json will go out of sync.

**Comment by mikeal** [comment]
This project is specifically designed for a workflow that publishes every merge into the master branch.

What you’re proposing is different enough that it’s actually just a different project. It sounds like what you want is something more along the lines of @bcoe’s https://github.com/googleapis/release-please

**Comment by mikeal** [comment]
> Otherwise, the published version and the version in the package.json will go out of sync.

This is by design because when you’re publishing every commit it ends up being very noisy to commit version changes, and it also reduces the utility of version commits to zero.

Instead, the standard practice is to set the version to `0.0.0-dev` in `master`.

Also, it should be noted that there actually *is* a version change commit that is part of the tag that gets pushed, so the tag actually *does* have the proper version in package.json, it just isn’t in master.
